version: '3'
services:
  app:
    build: .
    command: 'rails s'
    volumes:
      - .:/app
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mysql:8.0.11
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
