version: '3.1'
services:
  managearrears:
    image: managearrears
    environment:
    - AUTH_NO_AZURE_AD=true
    - INCOME_API_URL=http://incomeapi:3000/api/
    - TENANCY_API_URL=http://tenancyapi:80/api
    working_dir: /app
    command: sh -c 'cd /app && rails s'
    volumes:
      - ${PWD}:/app
    ports:
      - 3200:3000
    depends_on:
      - incomeapi
