module Hackney
  module Income
    class ActionDiaryEntryCodes
      def self.all_code_options
        [
          { name: 'Arrears Cleared', code: 'Z00', user_accessible: false },
          { name: 'Old Stage One', code: '1RS', user_accessible: false },
          { name: 'Old Stage Two', code: '2RS', user_accessible: false },
          { name: 'Agreement brought up-to-date', code: 'AGR', user_accessible: false },
          { name: 'Old Stage Three', code: '3RS', user_accessible: false },
          { name: 'Old Stage Four', code: '4RS', user_accessible: false },
          { name: 'Reset Stage Four', code: 'RR4', user_accessible: false },
          { name: 'Stage One Complete', code: 'ZR1', user_accessible: false },
          { name: 'Stage Two Complete', code: 'ZR2', user_accessible: false },
          { name: 'Stage Three Complete', code: 'ZR3', user_accessible: false },
          { name: 'Legal Referral Complete', code: 'ZL4', user_accessible: false },
          { name: 'Stage One (T)', code: '1TS', user_accessible: false },
          { name: 'Stage Two (T)', code: '2TS', user_accessible: false },
          { name: 'Eviction', code: '5TA', user_accessible: false },
          { name: 'Court Proceedings Complete', code: 'ZT4', user_accessible: false },
          { name: 'Eviction Complete', code: 'ZT5', user_accessible: false },
          { name: 'Pre-Court Complete', code: 'ZR5', user_accessible: false },
          { name: 'Old Breached Agreement (0)', code: '0RA', user_accessible: false },
          { name: 'Pre Court', code: '5RP', user_accessible: false },
          { name: 'Court Proceedings', code: '4TC', user_accessible: false },
          { name: 'Stage Four Complete', code: 'ZR4', user_accessible: false },
          { name: 'Stage One Complete', code: 'ZT1', user_accessible: false },
          { name: 'Old Breached Agreement (1)', code: '1RA', user_accessible: false },
          { name: 'Old Breached Agreement (2)', code: '2RA', user_accessible: false },
          { name: 'Old Breached Agreement (3)', code: '3RA', user_accessible: false },
          { name: 'Breached Order', code: '6RO', user_accessible: false },
          { name: 'Breached Agreement 1L', code: '1LA', user_accessible: false },
          { name: 'Stage One (L)', code: '1LS', user_accessible: false },
          { name: 'Stage Two Complete', code: 'Z01', user_accessible: false },
          { name: 'Stage Two (L)', code: '1RS', user_accessible: false },
          { name: 'General Diary Note', code: '2RS', user_accessible: false },
          { name: 'Stage Three (L)', code: 'AGR', user_accessible: false },
          { name: 'Legal Referral', code: '3RS', user_accessible: false },
          { name: 'Breached Agreement 0L', code: '4RS', user_accessible: false },
          { name: 'Breached Agreement 3L', code: 'RR5', user_accessible: false },
          { name: 'Breached Agreement 2L', code: 'ZR4', user_accessible: false },
          { name: 'Breached Agreement 4L', code: 'ZR5', user_accessible: false },
          { name: 'Stage One Complete', code: 'ZR6', user_accessible: false },
          { name: 'Stage Two Complete', code: 'ZL5', user_accessible: false },
          { name: 'Stage Three Complete', code: '1TS', user_accessible: false },
          { name: 'Court Proceedings Complete', code: '2TS', user_accessible: false },
          { name: 'Stage Three (T)', code: '5TA', user_accessible: false },
          { name: 'Breached Agreement', code: 'ZT6', user_accessible: false },
          { name: 'Stage Three Complete', code: 'ZT7', user_accessible: false },
          { name: 'Outright Possession Order', code: 'ZR6', user_accessible: false },
          { name: 'Unsuccessful Visit', code: '0RA', user_accessible: true },
          { name: 'Visit Made', code: '5RP', user_accessible: true },
          { name: 'Costs Awarded', code: '4TC', user_accessible: false },
          { name: 'Eviction Complete', code: 'ZR5', user_accessible: false },
          { name: 'Money Judgement Awarded', code: 'ZT2', user_accessible: false },
          { name: 'Charge Against Property', code: '1RA', user_accessible: false },
          { name: 'Suspended Possession', code: '2RA', user_accessible: false },
          { name: 'Postponed Possession', code: '3RA', user_accessible: false },
          { name: 'Adjourned Generally', code: '6RO', user_accessible: false },
          { name: 'Adjourned on Terms', code: '1LA', user_accessible: false },
          { name: 'DWP Direct Payments Requested', code: '1LS', user_accessible: false },
          { name: 'HB Outstanding', code: 'Z02', user_accessible: true },
          { name: 'DWP Direct Payments Refused', code: '1RS', user_accessible: false },
          { name: 'DWP Direct Payments Being Made', code: '2RS', user_accessible: false },
          { name: 'DWP Direct Payments Terminated', code: 'AGR', user_accessible: false },
          { name: 'Money Judgement Requested', code: '3RS', user_accessible: false },
          { name: 'Eviction', code: '4RS', user_accessible: false },
          { name: 'Dispute', code: 'RR6', user_accessible: false },
          { name: 'Complaint Received', code: 'ZR7', user_accessible: false },
          { name: 'Complaint Resolved', code: 'ZR8', user_accessible: false },
          { name: 'Notice Served', code: 'ZR9', user_accessible: true },
          { name: 'Introductory Tenancy to Secure', code: 'ZL6', user_accessible: false },
          { name: 'Voluntary Attach. of Earnings', code: '1TS', user_accessible: false },
          { name: 'Involuntary Att. of Earnings', code: '2TS', user_accessible: false },
          { name: 'Warrant of Exec. Applied for', code: '5TA', user_accessible: false },
          { name: 'Notice of Extension Served', code: 'ZT8', user_accessible: false },
          { name: 'Eviction', code: 'ZT9', user_accessible: false },
          { name: 'Breached Agreement (1)', code: 'ZR7', user_accessible: false },
          { name: 'Referred to Moorcroft', code: '0RA', user_accessible: false },
          { name: 'Direct Debit new sign up', code: '5RP', user_accessible: false },
          { name: 'Direct Debit Cancelled', code: '4TC', user_accessible: true },
          { name: 'Now a Former Tenants Account', code: 'ZR6', user_accessible: false },
          { name: 'FTA ARREARS AGREEMENT', code: 'ZT3', user_accessible: false },
          { name: 'Changes to DirectDebit payment', code: '1RA', user_accessible: false },
          { name: 'First contact with NOK', code: '2RA', user_accessible: false },
          { name: 'Subsequent contact with NOK', code: '3RA', user_accessible: false },
          { name: 'Breached Agreement (2)', code: '6RO', user_accessible: false },
          { name: 'Returned by Moorcroft', code: '1LA', user_accessible: false },
          { name: 'First FTA letter sent', code: '1LS', user_accessible: false },
          { name: 'Second FTA reminder', code: 'Z03', user_accessible: false },
          { name: 'FTA Debt Agency warning', code: '1RS', user_accessible: false },
          { name: 'Financial Inclusion Visit', code: '2RS', user_accessible: true },
          { name: 'Financial Inclusion Call', code: 'AGR', user_accessible: true },
          { name: 'Financial Inclusion Interview', code: '3RS', user_accessible: true },
          { name: 'Out of hours call', code: '4RS', user_accessible: true },
          { name: 'Breached Agreement (3)', code: 'RR7', user_accessible: false },
          { name: 'Office interview', code: 'ZR10', user_accessible: true },
          { name: 'Diirect Debit Payment', code: 'ZR11', user_accessible: false },
          { name: 'FTA Broken Agreement', code: 'ZR12', user_accessible: false },
          { name: 'S01 Stage One', code: 'ZL7', user_accessible: false },
          { name: 'S02 Stage Two', code: '1TS', user_accessible: false },
          { name: 'S03 Stage Three', code: '2TS', user_accessible: false },
          { name: 'S04 Stage Four', code: '5TA', user_accessible: false },
          { name: 'S05 Court', code: 'ZT10', user_accessible: false },
          { name: 'S06 Breach Court Order', code: 'ZT11', user_accessible: false },
          { name: 'S0A Alternative Letter', code: 'ZR8', user_accessible: false },
          { name: 'Court Proceedings', code: '0RA', user_accessible: false },
          { name: 'Write Off - Uneconomical', code: '5RP', user_accessible: false },
          { name: 'Write Off - Vulnerable/Infirm', code: '4TC', user_accessible: false },
          { name: 'Write Off - Deceased', code: 'ZR7', user_accessible: false },
          { name: 'Write Off - Address Unknown', code: 'ZT4', user_accessible: false },
          { name: 'Write Off - Dispute unresolved', code: '1RA', user_accessible: false },
          { name: 'Write Off - All action failed', code: '2RA', user_accessible: false },
          { name: 'Write Off - FT on Prison', code: '3RA', user_accessible: false },
          { name: 'Vunerable', code: '6RO', user_accessible: false },
          { name: 'Eviction Complete', code: '1LA', user_accessible: false },
          { name: 'Referred for debt advice', code: '1LS', user_accessible: true },
          { name: 'Repairs', code: 'Z04', user_accessible: false },
          { name: 'Possible abandonment', code: '1RS', user_accessible: false },
          { name: 'TMO a/c - no action required', code: '2RS', user_accessible: false },
          { name: 'FTA Refund Request Letter Sent', code: 'AGR', user_accessible: false },
          { name: 'Arrears mail merge letter sent', code: '3RS', user_accessible: false },
          { name: 'Universal Credit', code: '4RS', user_accessible: false },
          { name: 'Text message sent', code: 'RR8', user_accessible: false },
          { name: 'Actual Cost Breakdown Sent', code: 'ZR13', user_accessible: false },
          { name: 'TA New Account checks', code: 'ZR14', user_accessible: false },
          { name: 'Outcome of rent arrears panel', code: 'ZR15', user_accessible: false },
          { name: 'Pre legal action visit', code: 'ZL8', user_accessible: false },
          { name: 'Pre eviction contact outcome', code: '1TS', user_accessible: false },
          { name: 'Pre notice interview', code: '2TS', user_accessible: false },
          { name: 'Rent Arrears Panel Outcome', code: '5TA', user_accessible: false },
          { name: 'Referred to Credit Gee', code: 'ZT12', user_accessible: false },
          { name: 'Returned by Credit Gee', code: 'ZT13', user_accessible: false },
          { name: 'FTA - TO BE TRACED', code: 'ZR9', user_accessible: false },
          { name: 'Incoming telephone call', code: '0RA', user_accessible: true },
          { name: 'Outgoing telephone call', code: '5RP', user_accessible: true },
          { name: 'REFERRED TO VIL COLLECTIONS', code: '4TC', user_accessible: false },
          { name: 'REFERRED TO LEWIS DEBT AGENCY', code: 'ZR8', user_accessible: false },
          { name: 'RETURNED BY VIL COLLECTIONS', code: 'ZT5', user_accessible: false },
          { name: 'RETURNED BY LEWIS DEBT AGENCY', code: '1RA', user_accessible: false },
          { name: 'ACTION ON HOLD', code: '2RA', user_accessible: false },
          { name: 'HB INVESTIGATION PENDING', code: '3RA', user_accessible: false },
          { name: 'Returned by Credit Gee', code: '6RO', user_accessible: false }
        ]
      end

      def self.code_dropdown_options
        res = []
        all_code_options.each do |opt|
          res << [opt[:name], opt[:code]] if opt[:user_accessible]
        end

        res.sort_by { |i| i[0] }
      end
    end
  end
end
